# aitgon: This file is not running, so there is not point to have it
#name: CI
#
#on: [push]
#
#jobs:
#  build-linux:
#
#    runs-on: ubuntu-latest
#
#    strategy:
#      max-parallel: 5
#      matrix:
#        python-version: [3.7, 3.8, 3.9, 3.10.0, 3.11]
#
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        lfs: false
#    - name: Set up Python
#      uses: actions/setup-python@v2
#      with:
#        python-version: ${{ matrix.python-version }}
#    - name: Setup environment
#      run: |
#          export PATH="/usr/share/miniconda/bin:$PATH"
#          conda create -q -n multixrank
#          source activate multixrank
#          conda env update -f environment.yml
#    - name: Run tests
#      env:
#        CI: true
#      run: |
#        # activate conda env
#        export PATH="/usr/share/miniconda/bin:$PATH"
#        source activate multixrank
#        python -m unittest discover -v -f
